import {
  Button,
  ChakraProvider,
  Container,
  Flex,
  HStack,
  Heading,
  Input,
  Text,
} from "@chakra-ui/react";
import axios from "axios";
import Head from "next/head";
import { useState } from "react";

export default function Home() {
  const [searchText, setSearchText] = useState("");
  const [loading, setLoading] = useState(false);
  const [aboutUs, setAboutUs] = useState("");

  const handleSubmit = async () => {
    setLoading(true);
    try {
      const res = await axios.get(
        `/api/company-info?companyName=${searchText}`
      );
      setAboutUs(res.data.aboutUs);
    } catch {
      setAboutUs("Unable to fetch");
    }
    setLoading(false);
  };

  return (
    <ChakraProvider>
      <Head>
        <title>About Us Scraper</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container h="100vh">
          <Flex
            justify="center"
            align="center"
            flexDirection="column"
            h="100%"
            gap="1em"
          >
            <Heading as="h3" size="xl" textAlign="center">
              About Us Scrapper
            </Heading>
            <HStack>
              <Input
                placeholder="Search by Company Name"
                onChange={(e) => setSearchText(e.target.value)}
                value={searchText}
              />
              <Button onClick={handleSubmit} isLoading={loading}>
                Submit
              </Button>
            </HStack>
            <Text>{aboutUs}</Text>
          </Flex>
        </Container>
      </main>
    </ChakraProvider>
  );
}
